Refactored all hard-coded references to /var/ida to be agnostic regarding deployment location
Refactored utility scripts to always execute with correct user

diff --git a/nextcloud/apps/ida/src/l10n/utils/extract-api-response-strings b/nextcloud/apps/ida/src/l10n/utils/extract-api-response-strings
--- a/nextcloud/apps/ida/src/l10n/utils/extract-api-response-strings
+++ b/nextcloud/apps/ida/src/l10n/utils/extract-api-response-strings
@@ -1,7 +1,18 @@
 #!/bin/bash
 
+IDA_ROOT="/usr/local/fd/ida-fairdata-v3"
+
+if [ ! -d "$IDA_ROOT" ]; then
+    IDA_ROOT="/var/ida"
+fi
+
+if [ ! -d "$IDA_ROOT" ]; then
+    echo "Error: IDA root directory not found."
+    exit 1
+fi  
+
 # Base directory to search
-BASE_DIR="/var/ida/nextcloud/apps/ida/lib"
+BASE_DIR="$IDA_ROOT/nextcloud/apps/ida/lib"
 
 # Execute the find command with exclusions and extract translations
 find "$BASE_DIR" \
@@ -14,4 +25,4 @@ find "$BASE_DIR" \
     grep -v '$e->getMessage(' | \
     sed -E "s/^['\"]\s*//" | \
     sed -E "s/\s*['\"]$//" | \
-    sort -u > /var/ida/nextcloud/apps/ida/src/l10n/utils/api_response_strings.txt
+    sort -u > $IDA_ROOT/nextcloud/apps/ida/src/l10n/utils/api_response_strings.txt
diff --git a/nextcloud/apps/ida/src/l10n/utils/extract-translated-strings b/nextcloud/apps/ida/src/l10n/utils/extract-translated-strings
--- a/nextcloud/apps/ida/src/l10n/utils/extract-translated-strings
+++ b/nextcloud/apps/ida/src/l10n/utils/extract-translated-strings
@@ -1,12 +1,23 @@
 #!/bin/bash
 
+IDA_ROOT="/usr/local/fd/ida-fairdata-v3"
+
+if [ ! -d "$IDA_ROOT" ]; then
+    IDA_ROOT="/var/ida"
+fi
+
+if [ ! -d "$IDA_ROOT" ]; then
+    echo "Error: IDA root directory not found."
+    exit 1
+fi  
+
 # Base directory to search
-BASE_DIR="/var/ida/nextcloud"
+BASE_DIR="$IDA_ROOT/nextcloud"
 
 # Exclude directories
 EXCLUDE_DIRS=(
-    "/var/ida/nextcloud/3rdparty"
-    "/var/ida/nextcloud/apps/idaui-cleanup"
+    "$IDA_ROOT/nextcloud/3rdparty"
+    "$IDA_ROOT/nextcloud/apps/idaui-cleanup"
 )
 
 # Build the find exclude arguments
@@ -21,5 +32,5 @@ find "$BASE_DIR" \
     \( -name "*.js" -o -name "*.php" \) -type f -exec \
     grep -Eho "t\(['\"]ida['\"],\s*['\"][^'\"]+['\"]\)" {} + | \
     sed -E "s/^t\(['\"]ida['\"],\s*['\"]([^'\"]+)['\"]\)/\1/" | \
-    sort -u > /var/ida/nextcloud/apps/ida/src/l10n/utils/translated_strings.txt
+    sort -u > $IDA_ROOT/nextcloud/apps/ida/src/l10n/utils/translated_strings.txt
 
diff --git a/nextcloud/apps/ida/src/l10n/utils/find-missing-translation-strings b/nextcloud/apps/ida/src/l10n/utils/find-missing-translation-strings
--- a/nextcloud/apps/ida/src/l10n/utils/find-missing-translation-strings
+++ b/nextcloud/apps/ida/src/l10n/utils/find-missing-translation-strings
@@ -1,15 +1,27 @@
 #!/bin/bash
 
-TRANSLATIONS_FILE="/var/ida/nextcloud/apps/ida/src/l10n/translations.json"
+
+IDA_ROOT="/usr/local/fd/ida-fairdata-v3"
+
+if [ ! -d "$IDA_ROOT" ]; then
+    IDA_ROOT="/var/ida"
+fi
+
+if [ ! -d "$IDA_ROOT" ]; then
+    echo "Error: IDA root directory not found."
+    exit 1
+fi  
+
+TRANSLATIONS_FILE="$IDA_ROOT/nextcloud/apps/ida/src/l10n/translations.json"
 
 # Build full strings list
-cat /var/ida/nextcloud/apps/ida/src/l10n/utils/*_strings.txt | sort -u > /tmp/$$.strings.txt
+cat $IDA_ROOT/nextcloud/apps/ida/src/l10n/utils/*_strings.txt | sort -u > /tmp/$$.strings.txt
 
 # Extract keys from the JSON file
 jq -r 'keys[]' "$TRANSLATIONS_FILE" > /tmp/$$.translations_keys.txt
 
 # Find strings in the first file that are not in the keys of the JSON dictionary
-grep -Fxvf /tmp/$$.translations_keys.txt /tmp/$$.strings.txt > /var/ida/nextcloud/apps/ida/src/l10n/utils/missing_translation_strings.txt
+grep -Fxvf /tmp/$$.translations_keys.txt /tmp/$$.strings.txt > $IDA_ROOT/nextcloud/apps/ida/src/l10n/utils/missing_translation_strings.txt
 
 # Output the result
 echo "Strings not found in '$TRANSLATIONS_FILE' saved in 'missing_translation_strings.txt'."
diff --git a/nextcloud/apps/ida/src/l10n/utils/generate-translations b/nextcloud/apps/ida/src/l10n/utils/generate-translations
--- a/nextcloud/apps/ida/src/l10n/utils/generate-translations
+++ b/nextcloud/apps/ida/src/l10n/utils/generate-translations
@@ -1,8 +1,19 @@
 #!/bin/bash
 
+IDA_ROOT="/usr/local/fd/ida-fairdata-v3"
+
+if [ ! -d "$IDA_ROOT" ]; then
+    IDA_ROOT="/var/ida"
+fi
+
+if [ ! -d "$IDA_ROOT" ]; then
+    echo "Error: IDA root directory not found."
+    exit 1
+fi  
+
 # Input files
-STRING_LIST_FILE="/var/ida/nextcloud/apps/ida/src/l10n/utils/translated_strings.txt"
-JSON_FILE="/var/ida/nextcloud/apps/ida/src/l10n/utils/translations_old.json"
+STRING_LIST_FILE="$IDA_ROOT/nextcloud/apps/ida/src/l10n/utils/translated_strings.txt"
+JSON_FILE="$IDA_ROOT/nextcloud/apps/ida/src/l10n/utils/translations_old.json"
 
 # Check if both files exist
 if [[ ! -f "$STRING_LIST_FILE" || ! -f "$JSON_FILE" ]]; then
@@ -36,5 +47,5 @@ jq --argjson keys "[$keys]" '
     ) |
     # Sort the output object by keys
     to_entries | sort_by(.key) | from_entries
-' "$JSON_FILE" | jq . --indent 4 > /var/ida/nextcloud/apps/ida/src/l10n/utils/translations.json
+' "$JSON_FILE" | jq . --indent 4 > $IDA_ROOT/nextcloud/apps/ida/src/l10n/utils/translations.json
 
diff --git a/tests/run-tests b/tests/run-tests
--- a/tests/run-tests
+++ b/tests/run-tests
@@ -42,10 +42,54 @@
 # run-tests cli          run command line tools behavioral tests
 #
 #--------------------------------------------------------------------------------
+# Ensure script is run as apache
 
+ID=$(id -u -n)
+if [ "$ID" != "apache" ]; then
+    sudo -u apache "$0" "$@"
+    exit
+fi
+
+#--------------------------------------------------------------------------------
 # Only use the core os versions of commands
+
 PATH="/usr/bin:/bin:/usr/sbin:/sbin"
 export PATH
+
+#--------------------------------------------------------------------------------
+# Load configuration
+
+CONFIG_FILE=$(dirname $(realpath "$0"))/../config/config.sh
+
+if [ -e $CONFIG_FILE ]
+then
+    source $CONFIG_FILE
+else
+    echo "The configuration file $CONFIG_FILE cannot be found. Aborting." >&2
+    exit 1
+fi
+
+if [ "$ROOT" = "" ]; then
+    echo "The configuration variable $ROOT has not been defined Aborting." >&2
+    exit 1
+fi
+
+if [ "$IDA_ENVIRONMENT" == "PRODUCTION" ]; then
+    echo "This script can not be run in a production environment. Aborting." >&2
+    exit 1
+fi
+
+CONSTANTS_FILE=$ROOT/lib/constants.sh
+
+if [ -e $CONSTANTS_FILE ]
+then
+    source $CONSTANTS_FILE
+else
+    echo "The service constants file $CONSTANTS_FILE cannot be found. Aborting." >&2
+    exit 1
+fi
+
+#--------------------------------------------------------------------------------
 
 START_TIME=$(date +%s)
 
@@ -74,59 +118,6 @@ function report_success {
     echo ""
 }
 
-function fix_dev_permissions {
-    # If in development environment, relax permissions allowing code updates if
-    # the DEV_PERMISSIONS variable is defined in user's environment
-    if [ "$ENVIRONMENT" = "DEV" ]; then
-        if [ "$DEV_PERMISSIONS" ]; then
-            chmod -R "$DEV_PERMISSIONS" "$ROOT"
-        fi
-    fi
-}
-
-# Load service constants and configuration settings
-
-PARENT_FOLDER=$(dirname "$(realpath $0)")
-PARENT_BASENAME=$(basename "$PARENT_FOLDER")
-
-while [ "$PARENT_BASENAME" != "ida" -a "$PARENT_BASENAME" != "" ]; do
-    PARENT_FOLDER=$(dirname "$PARENT_FOLDER")
-    PARENT_BASENAME=$(basename "$PARENT_FOLDER")
-done
-
-CONSTANTS_FILE="$PARENT_FOLDER/lib/constants.sh"
-
-if [ -e $CONSTANTS_FILE ]
-then
-    . $CONSTANTS_FILE
-else
-    echo "The service constants file $CONSTANTS_FILE cannot be found. Aborting." >&2
-    exit 1
-fi
-
-CONFIG_FILE="$PARENT_FOLDER/config/config.sh"
-
-if [ -e $CONFIG_FILE ]
-then
-    . $CONFIG_FILE
-else
-    echo "The configuration file $CONFIG_FILE cannot be found. Aborting." >&2
-    exit 1
-fi
-
-if [ "$ROOT" = "" ]; then
-    echo "The configuration variable $ROOT has not been defined Aborting." >&2
-    exit 1
-fi
-
-#--------------------------------------------------------------------------------
-# Verify that we are in a test environment
-
-if [ "$IDA_ENVIRONMENT" == "PRODUCTION" ]; then
-    echo "This script can not be run in a production environment. Aborting." >&2
-    exit 1
-fi
-
 #--------------------------------------------------------------------------------
 # Flush replicated files, if so configured
 
@@ -145,14 +136,14 @@ rm -f $STORAGE_OC_DATA_ROOT/control/LOCK    2>/dev/null
 rm -f $STORAGE_OC_DATA_ROOT/control/OFFLINE 2>/dev/null
 
 #--------------------------------------------------------------------------------
+# Ensure correct permissions
+
+$ROOT/utils/fix-permissions
+
+#--------------------------------------------------------------------------------
 # Ensure test python environment is properly configured and active
 
 source $ROOT/venv/bin/activate
-
-#--------------------------------------------------------------------------------
-# Ensure correct permissions
-
-source $ROOT/utils/fix-permissions
 
 #--------------------------------------------------------------------------------
 # Execute tests per the provided command line arguments
@@ -160,19 +151,6 @@ source $ROOT/utils/fix-permissions
 cd $ROOT
 
 if [ $# -ge 1 ]; then
-
-    if [ "$1" = "agents" ]; then
-
-        echo "UNIT TESTS:"
-
-        python -W ignore -m unittest discover -f -q agents
-
-        if [ $? -ne 0 ]; then
-            exit 1
-        fi
-    fi
-
-    echo "BEHAVIORAL TESTS:"
 
     python -W ignore -m unittest discover -f -q tests.$1
 
@@ -183,16 +161,6 @@ if [ $# -ge 1 ]; then
     report_success
 
 else
-
-    echo "UNIT TESTS:"
-
-    python -W ignore -m unittest discover -f -q agents
-
-    if [ $? -ne 0 ]; then
-        exit 1
-    fi
-
-    echo "BEHAVIORAL TESTS:"
 
     python -W ignore -m unittest discover -f -q tests.admin
 
@@ -245,5 +213,3 @@ else
     report_success
 
 fi
-
-fix_dev_permissions
diff --git a/update/backup-old-database b/update/backup-old-database
--- a/update/backup-old-database
+++ b/update/backup-old-database
@@ -3,7 +3,16 @@
 # This script backs up the DBNAME_OLD database to a subdirectory named 'backup' in the defined
 # IDA_UPDATE_ROOT folder.
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 echo "Backing up old database ..."
 
diff --git a/update/create-dummy-user-directories b/update/create-dummy-user-directories
--- a/update/create-dummy-user-directories
+++ b/update/create-dummy-user-directories
@@ -6,19 +6,28 @@
 # database defines all the current users but there is no actual data on disk for those users in the
 # non-production environment.
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 for USER in $USERS; do
     echo "Creating dummy home directories for user ${USER} ..."
     HOME_DIR="${STORAGE_OC_DATA_ROOT}/${USER}"
     if [ ! -d "${HOME_DIR}" ]; then
-        sudo -u apache mkdir "${HOME_DIR}" 
+        mkdir "${HOME_DIR}" 
         echo "    ${HOME_DIR} created"
     else
         echo "    ${HOME_DIR} exists"
     fi
     if [ ! -d "${HOME_DIR}/files" ]; then
-        sudo -u apache mkdir "${HOME_DIR}/files" 
+        mkdir "${HOME_DIR}/files" 
         echo "    ${HOME_DIR}/files created"
     else
         echo "    ${HOME_DIR}/files exists"
@@ -27,13 +36,13 @@ for USER in $USERS; do
     if [ "$PSO_USER" ]; then
         PROJECT=$(echo "$PSO_USER" | sed -e 's/^PSO_//')
         if [ ! -d "${HOME_DIR}/files/${PROJECT}" ]; then
-            sudo -u apache mkdir "${HOME_DIR}/files/${PROJECT}" 
+            mkdir "${HOME_DIR}/files/${PROJECT}" 
             echo "    ${HOME_DIR}/files/${PROJECT} created"
         else
             echo "    ${HOME_DIR}/files/${PROJECT} exists"
         fi
         if [ ! -d "${HOME_DIR}/files/${PROJECT}+" ]; then
-            sudo -u apache mkdir "${HOME_DIR}/files/${PROJECT}+" 
+            mkdir "${HOME_DIR}/files/${PROJECT}+" 
             echo "    ${HOME_DIR}/files/${PROJECT}+ created"
         else
             echo "    ${HOME_DIR}/files/${PROJECT}+ exists"
diff --git a/update/export-data-from-old-database b/update/export-data-from-old-database
--- a/update/export-data-from-old-database
+++ b/update/export-data-from-old-database
@@ -2,7 +2,16 @@
 #
 # This script will export all essential data from the old database.
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 # Ensure DBDATA is defined in configuration, and that the subdirectory exists
 if [[ -z "$DBDATA" ]]; then
@@ -70,7 +79,7 @@ function export_table() {
         echo "Error: The output file ${csv_file} does not exist" >&2
         exit 1
     fi
-    local exported_record_count=$(/var/ida/update/count-csv-records < "${csv_file}")
+    local exported_record_count=$($ROOT/update/count-csv-records < "${csv_file}")
     if [ "$exported_record_count" = "0" ]; then
         echo "Error: The output file ${csv_file} is empty" >&2
         exit 1
diff --git a/update/extract-baseline-validation-data b/update/extract-baseline-validation-data
--- a/update/extract-baseline-validation-data
+++ b/update/extract-baseline-validation-data
@@ -10,7 +10,16 @@
 #
 # Strict assumptions are made about the location of necessary scripts; update if/as needed.
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 echo "--- Extracting baseline validation data ..."
 
@@ -86,7 +95,7 @@ for PROJECT in $PROJECTS; do
         continue
     fi
 
-    /var/ida/update/extract-project-data "$PROJECT" "$OLDDATA" "$TMPDIR" 2>"$ERR"
+    $ROOT/update/extract-project-data "$PROJECT" "$OLDDATA" "$TMPDIR" 2>"$ERR"
 
     EXIT_CODE=$?
 
@@ -109,7 +118,7 @@ for USER in $USERS; do
         continue
     fi
 
-    /var/ida/update/extract-user-data "$USER" "$OLDDATA" "$TMPDIR" 2>"$ERR"
+    $ROOT/update/extract-user-data "$USER" "$OLDDATA" "$TMPDIR" 2>"$ERR"
 
     EXIT_CODE=$?
 
diff --git a/update/extract-migrated-validation-data-if-diffs b/update/extract-migrated-validation-data-if-diffs
--- a/update/extract-migrated-validation-data-if-diffs
+++ b/update/extract-migrated-validation-data-if-diffs
@@ -8,7 +8,16 @@
 #
 # Strict assumptions are made about the location of git repositories; update as needed.
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 echo "--- Extracting migrated validation data ..."
 
@@ -59,7 +68,7 @@ for PROJECT in $PROJECTS; do
         continue
     fi
 
-    /var/ida/update/extract-project-data "$PROJECT" "$NEWDATA" "$TMPDIR" 2>"$ERR"
+    $ROOT/update/extract-project-data "$PROJECT" "$NEWDATA" "$TMPDIR" 2>"$ERR"
 
     EXIT_CODE=$?
 
@@ -89,7 +98,7 @@ for USER in $USERS; do
         continue
     fi
 
-    /var/ida/update/extract-user-data "$USER" "$NEWDATA" "$TMPDIR" 2>"$ERR"
+    $ROOT/update/extract-user-data "$USER" "$NEWDATA" "$TMPDIR" 2>"$ERR"
 
     if [ -s "$ERR" ]; then
         cat "$ERR" >&2
diff --git a/update/extract-migrated-validation-data-resume b/update/extract-migrated-validation-data-resume
--- a/update/extract-migrated-validation-data-resume
+++ b/update/extract-migrated-validation-data-resume
@@ -7,7 +7,16 @@
 
 # !!! THIS IS A MODIFIED VERSION THAT WILL NOT RE-EXTRACT EXISTING DATA
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 echo "--- Extracting migrated validation data ..."
 
@@ -52,7 +61,7 @@ for PROJECT in $PROJECTS; do
         continue
     fi
 
-    /var/ida/update/extract-project-data "$PROJECT" "$NEWDATA" "$TMPDIR" 2>"$ERR"
+    $ROOT/update/extract-project-data "$PROJECT" "$NEWDATA" "$TMPDIR" 2>"$ERR"
 
     EXIT_CODE=$?
 
@@ -80,7 +89,7 @@ for USER in $USERS; do
         continue
     fi
 
-    /var/ida/update/extract-user-data "$USER" "$NEWDATA" "$TMPDIR" 2>"$ERR"
+    $ROOT/update/extract-user-data "$USER" "$NEWDATA" "$TMPDIR" 2>"$ERR"
 
     EXIT_CODE=$?
 
diff --git a/update/import-data-into-new-database b/update/import-data-into-new-database
--- a/update/import-data-into-new-database
+++ b/update/import-data-into-new-database
@@ -5,7 +5,16 @@
 #
 # Strict assumptions are made about the location of git repositories; update as needed.
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 # Ensure DBNAME_NEW and DBNAME_OLD are defined in configuration and not the same
 if [[ -z "$DBNAME_NEW" ]]; then
@@ -76,7 +85,7 @@ function import_table() {
         echo "Error: The file ${csv_file} does not exist" >&2
         exit 1
     fi
-    local expected_record_count=$(/var/ida/update/count-csv-records < "$csv_file")
+    local expected_record_count=$($ROOT/update/count-csv-records < "$csv_file")
     if [ "$expected_record_count" = "0" ]; then
         echo "Error: The file ${csv_file} is empty" >&2
         exit 1
diff --git a/update/install-new-nextcloud b/update/install-new-nextcloud
--- a/update/install-new-nextcloud
+++ b/update/install-new-nextcloud
@@ -1,9 +1,18 @@
 #!/bin/bash
 #
 # This script will install a new version of Nextcloud, according to the current
-# configuration and contents of /var/ida, creating a new database.
+# configuration and contents of the cloned repository, creating a new database.
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 echo "Checking configuration ..."
 for VARIABLE in OCC DBTYPE DBNAME DBNAME_OLD DBHOST DBUSER DBPASSWORD NC_ADMIN_USER NC_ADMIN_PASS TMPDIR STORAGE_OC_DATA_ROOT; do
@@ -20,7 +29,7 @@ if [ "$DBNAME" = "$DBNAME_OLD" ]; then
 fi
 
 echo "Checking existing configuration files ..."
-for FILE in /var/ida/nextcloud/config/config.php /var/ida/nextcloud/.htaccess; do
+for FILE in $ROOT/nextcloud/config/config.php $ROOT/nextcloud/.htaccess; do
     if [ ! -e $FILE ]; then
         echo "The current Nextcloud file '$FILE' does not exist. Aborting."
         exit 1
@@ -37,11 +46,11 @@ if ! $PSQL -c "SELECT 1 FROM pg_database WHERE datname = '$DBNAME';" | grep -q 1
 fi
 
 echo "Backing up existing Nextcloud configurations ..."
-mv /var/ida/nextcloud/config/config.php "${TMPDIR}/config.php"
-mv /var/ida/nextcloud/.htaccess "${TMPDIR}/.htaccess"
+mv $ROOT/nextcloud/config/config.php "${TMPDIR}/config.php"
+mv $ROOT/nextcloud/.htaccess "${TMPDIR}/.htaccess"
 
 echo "Clearing default Nextcloud account files for new users ..."
-rm -fr /var/ida/nextcloud/core/skeleton/* 2>/dev/null
+rm -fr $ROOT/nextcloud/core/skeleton/* 2>/dev/null
 
 # NOTE: We specify a temporary empty directory as the data storage root for installation, so that the
 # existing data storage root is not touched by the Nextcloud installation process!!! 
@@ -73,23 +82,23 @@ if [ $? != 0 ]; then
 fi
 
 echo "Restoring original configuration ..."
-sudo -u apache cp "${TEMP_DATA_ROOT}/.ncdata" "$STORAGE_OC_DATA_ROOT"
-if [ -e /var/ida/nextcloud/config/config.php ]; then
+cp "${TEMP_DATA_ROOT}/.ncdata" "$STORAGE_OC_DATA_ROOT"
+if [ -e $ROOT/nextcloud/config/config.php ]; then
     rm -f "${INSTALL_ROOT}/config.php.install"
-    mv /var/ida/nextcloud/config/config.php "${INSTALL_ROOT}/config.php.install"
+    mv $ROOT/nextcloud/config/config.php "${INSTALL_ROOT}/config.php.install"
 fi
-if [ -e /var/ida/nextcloud/.htaccess ]; then
+if [ -e $ROOT/nextcloud/.htaccess ]; then
     rm -f "${INSTALL_ROOT}/.htaccess.install"
-    mv /var/ida/nextcloud/.htaccess "${INSTALL_ROOT}/.htaccess.install"
+    mv $ROOT/nextcloud/.htaccess "${INSTALL_ROOT}/.htaccess.install"
 fi
-cat "${TMPDIR}/.htaccess" > /var/ida/nextcloud/.htaccess
-cat "${TMPDIR}/config.php" > /var/ida/nextcloud/config/config.php
+cat "${TMPDIR}/.htaccess" > $ROOT/nextcloud/.htaccess
+cat "${TMPDIR}/config.php" > $ROOT/nextcloud/config/config.php
 
 echo "Ensuring IDA file permissions are correct ..."
-/var/ida/utils/fix-permissions
+$ROOT/utils/fix-permissions
 
 echo "Disabling unused Nextcloud apps ..."
-sudo -u apache /var/ida/utils/disable_nextcloud_apps
+$ROOT/utils/disable_nextcloud_apps
 
 echo "Enabling essential Nextcloud apps ..."
 $OCC app:enable files_sharing
@@ -97,7 +106,7 @@ $OCC app:enable admin_audit
 $OCC app:enable ida
 
 echo "Configuring essential Nextcloud settings ..."
-/var/ida/utils/initialize_nextcloud_settings
+$ROOT/utils/initialize_nextcloud_settings
 
 echo "Updating database indices and MIME types..."
 $OCC maintenance:repair --include-expensive
diff --git a/update/list-projects b/update/list-projects
--- a/update/list-projects
+++ b/update/list-projects
@@ -2,7 +2,17 @@
 #
 # This script will list all projects in the old database based on all PSO users
 
-. /var/ida/config/config.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+ROOT=$(dirname "$UPDATE_ROOT")
+CONFIG_FILE="$ROOT/config/config.sh"
+
+if [ ! -f "$CONFIG_FILE" ]; then
+    echo "ERROR: Could not find file $CONFIG_FILE"
+    exit 1
+fi
+
+source "$CONFIG_FILE"
 
 # Ensure DBNAME_OLD is defined in configuration
 if [[ -z "$DBNAME_OLD" ]]; then
diff --git a/update/migrate-data b/update/migrate-data
--- a/update/migrate-data
+++ b/update/migrate-data
@@ -2,17 +2,26 @@
 #
 # This script will perform the core of the data migration from the old to the new database. 
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 set -e # if anything fails, die die die
 
 echo "--- Migrating all data from $DBNAME_OLD to $DBNAME ..."
 
-/var/ida/update/export-data-from-old-database
-/var/ida/update/validate-exported-data
-/var/ida/update/import-data-into-new-database
-/var/ida/update/update-sequences
-/var/ida/update/update-indices
-/var/ida/update/wait-for-database-housekeeping
+$UPDATE_ROOT/export-data-from-old-database
+$UPDATE_ROOT/validate-exported-data
+$UPDATE_ROOT/import-data-into-new-database
+$UPDATE_ROOT/update-sequences
+$UPDATE_ROOT/update-indices
+$UPDATE_ROOT/wait-for-database-housekeeping
 
 echo "Migration completed."
diff --git a/update/reimport-missing-checksums b/update/reimport-missing-checksums
--- a/update/reimport-missing-checksums
+++ b/update/reimport-missing-checksums
@@ -13,7 +13,16 @@
 #
 # Strict assumptions are made about the location of git repositories; update as needed.
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 # Ensure DBNAME_NEW and DBNAME_OLD are defined in configuration and not the same
 if [[ -z "$DBNAME_NEW" ]]; then
@@ -63,7 +72,7 @@ echo "Generating checksum re-import SQL from ${DBDATA}oc_filecache.csv ... "
 
 cd "$DBDATA"
 
-/var/ida/update/generate-checksum-import-sql
+$UPDATE_ROOT/generate-checksum-import-sql
 
 echo "Re-importing any missing checksums into the oc_filecache table in $DBNAME_NEW ..."
 
diff --git a/update/rescan-cleanup b/update/rescan-cleanup
--- a/update/rescan-cleanup
+++ b/update/rescan-cleanup
@@ -9,7 +9,16 @@
 # disk even though the original production file cache records have been copied to the new
 # database.
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 if [ "$IDA_ENVIRONMENT" != "DEV" ]; then
     HOST_DOMAIN=$(hostname -f)
@@ -20,12 +29,12 @@ if [ "$IDA_ENVIRONMENT" != "DEV" ]; then
 fi
 
 echo "--- Cleaning file cache ..."
-sudo -u apache /var/ida/nextcloud/occ files:cleanup
+$OCC files:cleanup
 
 echo "--- Rescanning all data for all projects and users ..."
-sudo -u apache /var/ida/nextcloud/occ files:scan --all #-v
+$OCC files:scan --all #-v
 
 echo "--- Cleaning file cache again ..."
-sudo -u apache /var/ida/nextcloud/occ files:cleanup
+$OCC files:cleanup
 
 echo "Rescan / Cleanup completed."
diff --git a/update/reset-new-database b/update/reset-new-database
--- a/update/reset-new-database
+++ b/update/reset-new-database
@@ -15,7 +15,16 @@
 # It then updates the essential sequence values in the new database to be 1 greater than the
 # maximum value remaining in each relevant table in the new database.
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 echo "--- Resetting new database ..."
 
diff --git a/update/reset-reshare b/update/reset-reshare
--- a/update/reset-reshare
+++ b/update/reset-reshare
@@ -3,12 +3,22 @@
 # This script will reset all PSO passwords and reshare all PSO folders
 # so they are visible to all project users
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+ROOT=$(dirname "$UPDATE_ROOT")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 echo "--- Resetting all PSO passwords ..."
-sudo -u apache /var/ida/utils/reset_PSO_passwords
+$ROOT/utils/reset_PSO_passwords
 
 echo "--- Resharing all PSO folders ..."
-sudo -u apache /var/ida/utils/reshare_PSO_folders
+$ROOT/utils/reshare_PSO_folders
 
 echo "Reset / Reshare completed."
diff --git a/update/reset-test-user-password b/update/reset-test-user-password
--- a/update/reset-test-user-password
+++ b/update/reset-test-user-password
@@ -3,6 +3,16 @@
 # This script will reset the password of the specified user to the TEST_USER_PASS value
 # defined in config.sh. 
 
-. /var/ida/config/config.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+ROOT=$(dirname "$UPDATE_ROOT")
+INIT_FILE="$UPDATE_ROOT/init.sh"
 
-sudo -u apache OC_PASS="$TEST_USER_PASS" /var/ida/nextcloud/occ user:resetpassword "$1" --password-from-env
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
+
+OC_PASS="$TEST_USER_PASS" $ROOT/nextcloud/occ user:resetpassword "$1" --password-from-env
diff --git a/update/restore-old-database-from-backup b/update/restore-old-database-from-backup
--- a/update/restore-old-database-from-backup
+++ b/update/restore-old-database-from-backup
@@ -3,7 +3,16 @@
 # This script flushes and restores the DBNAME_OLD database from a dump file located in
 # the subdirectory named 'backup' in the defined IDA_UPDATE_ROOT folder.
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 if [[ -z "$IDA_UPDATE_ROOT" ]]; then
     echo "Error: Environment variable IDA_UPDATE_ROOT must be defined" >&2
diff --git a/update/test-migration b/update/test-migration
--- a/update/test-migration
+++ b/update/test-migration
@@ -7,9 +7,18 @@
 # If the parameter --full is given, the baseline validation data will be re-initialized and
 # re-extracted, else only the post-update migration steps will be executed
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
 
-mkdir "/var/ida/update/tests" 2>/dev/null
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
+
+mkdir "$UPDATE_ROOT/tests" 2>/dev/null
 
 set -e # if anything fails, die die die
 
@@ -26,21 +35,21 @@ if [ "$FULL" ]; then
 fi
 
 if [ -z "$NEW_ONLY" ]; then
-    /var/ida/update/reset-new-database
-    /var/ida/update/extract-baseline-validation-data
-    /var/ida/update/validate-baseline-data
+    $UPDATE_ROOT/reset-new-database
+    $UPDATE_ROOT/extract-baseline-validation-data
+    $UPDATE_ROOT/validate-baseline-data
 fi
 
 # Derived from migrate-data script, but with database reset and test options
-/var/ida/update/export-data-from-old-database --test
-/var/ida/update/validate-exported-data --test
-/var/ida/update/reset-new-database
-/var/ida/update/import-data-into-new-database --test
-/var/ida/update/update-sequences
-/var/ida/update/update-indices
-/var/ida/update/wait-for-database-housekeeping
-/var/ida/update/reset-reshare
-/var/ida/update/extract-migrated-validation-data
-/var/ida/update/validate-migrated-data
-/var/ida/update/rescan-cleanup
-/var/ida/update/reset-test-user-password fd_test_ida_user # for safe tests
+$UPDATE_ROOT/export-data-from-old-database --test
+$UPDATE_ROOT/validate-exported-data --test
+$UPDATE_ROOT/reset-new-database
+$UPDATE_ROOT/import-data-into-new-database --test
+$UPDATE_ROOT/update-sequences
+$UPDATE_ROOT/update-indices
+$UPDATE_ROOT/wait-for-database-housekeeping
+$UPDATE_ROOT/reset-reshare
+$UPDATE_ROOT/extract-migrated-validation-data
+$UPDATE_ROOT/validate-migrated-data
+$UPDATE_ROOT/rescan-cleanup
+$UPDATE_ROOT/reset-test-user-password fd_test_ida_user # for safe tests
diff --git a/update/update-indices b/update/update-indices
--- a/update/update-indices
+++ b/update/update-indices
@@ -7,7 +7,16 @@
 #
 # Strict assumptions are made about the location of git repositories; update as needed.
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 echo "--- Updating indices in new database and cleaning up ..."
 
diff --git a/update/update-sequences b/update/update-sequences
--- a/update/update-sequences
+++ b/update/update-sequences
@@ -5,7 +5,16 @@
 #
 # Not all sequences are essential to the migration and need updating.
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 echo "--- Updating database sequence values ..."
 
diff --git a/update/validate-exported-data b/update/validate-exported-data
--- a/update/validate-exported-data
+++ b/update/validate-exported-data
@@ -3,7 +3,17 @@
 # This script will validate all CSV files exported from the database to ensure
 # they have the correct number of fields, taking into account escaped commas.
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+ROOT=$(dirname "$UPDATE_ROOT")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 set -e # if anything fails, die die die
 
@@ -17,7 +27,7 @@ if [ ! -d "$DBDATA" ]; then
     exit 1;
 fi
 
-if [ ! -d /var/ida/venv ]; then
+if [ ! -d $ROOT/venv ]; then
     echo "Error: The python venv does not exist!" >&2;
     exit 1;
 fi
@@ -44,5 +54,5 @@ export OC_SHARE_FIELDS
 export OC_STORAGES_FIELDS
 export OC_USERS_FIELDS
 
-source /var/ida/venv/bin/activate
-python -u /var/ida/update/lib/validate_exported_data.py
+source $ROOT/venv/bin/activate
+python -u $ROOT/update/lib/validate_exported_data.py
diff --git a/update/wait-for-database-housekeeping b/update/wait-for-database-housekeeping
--- a/update/wait-for-database-housekeeping
+++ b/update/wait-for-database-housekeeping
@@ -3,7 +3,16 @@
 # This script will check for ongoing database housekeeping tasks and wait for them to finish, up to
 # a specified timeout. If the tasks are not finished within the timeout, the script will exit with an error.
 
-. /var/ida/update/init.sh
+SCRIPT_PATHNAME="$(realpath $0)"
+UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
+INIT_FILE="$UPDATE_ROOT/init.sh"
+
+if [ ! -f "$INIT_FILE" ]; then
+    echo "ERROR: Could not find file $INIT_FILE"
+    exit 1
+fi
+
+source "$INIT_FILE"
 
 echo "--- Waiting for database housekeeping operations to complete ..."
 
diff --git a/utils/disable_nextcloud_apps b/utils/disable_nextcloud_apps
--- a/utils/disable_nextcloud_apps
+++ b/utils/disable_nextcloud_apps
@@ -21,7 +21,28 @@
 # @license  GNU Affero General Public License, version 3
 # @link     https://www.fairdata.fi/en/ida
 #--------------------------------------------------------------------------------
+# Ensure script is run as apache
 
+ID=$(id -u -n)
+if [ "$ID" != "apache" ]; then
+    sudo -u apache "$0" "$@"
+    exit
+fi
+
+#--------------------------------------------------------------------------------
+# Load configuration
+
+SCRIPT_FOLDER=`dirname "$(realpath $0)"`
+CONFIG_FILE="$SCRIPT_FOLDER/../config/config.sh"
+
+if [ -e $CONFIG_FILE ]; then
+    . $CONFIG_FILE
+else
+    echo "The configuration file $CONFIG_FILE cannot be found. Aborting." >&2
+    exit 1
+fi
+
+#--------------------------------------------------------------------------------
 # The following apps are not used for IDA and are disabled in Nextcloud:
 
 APPS="activity \
@@ -59,36 +80,8 @@ APPS="activity \
       webhook_listeners \
       weather_status"
 
-SCRIPT_FOLDER=`dirname "$(realpath $0)"`
-CONFIG_FILE="$SCRIPT_FOLDER/../config/config.sh"
-
-if [ -e $CONFIG_FILE ]; then
-    . $CONFIG_FILE
-else
-    echo "The configuration file $CONFIG_FILE cannot be found. Aborting." >&2
-    exit 1
-fi
-
-#--------------------------------------------------------------------------------
-# Determine the apache user
-
-if [ -d /etc/httpd ]; then
-    HTTPD_USER="apache"
-else
-    HTTPD_USER="www-data"
-fi
-
-#--------------------------------------------------------------------------------
-# Ensure script is run as apache
-
-ID=`id -u -n`
-if [ "$ID" != "$HTTPD_USER" ]; then
-    echo "You must execute this script as $HTTPD_USER"
-    exit 1
-fi
-
 #--------------------------------------------------------------------------------
 
 for APP in $APPS; do
-    php /var/ida/nextcloud/occ app:disable $APP
+    php $ROOT/nextcloud/occ app:disable $APP
 done
diff --git a/utils/initialize_venv b/utils/initialize_venv
--- a/utils/initialize_venv
+++ b/utils/initialize_venv
@@ -21,16 +21,24 @@
 # @license  GNU Affero General Public License, version 3
 # @link     https://www.fairdata.fi/en/ida
 # --------------------------------------------------------------------------------
+# Ensure script is run as apache
 
-ID=`id -u -n`
-if [ "$ID" != "root" ]; then
-    echo "You must execute this script as root"
-    exit 1
+ID=$(id -u -n)
+if [ "$ID" != "apache" ]; then
+    sudo -u apache "$0" "$@"
+    exit
 fi
 
+#--------------------------------------------------------------------------------
+
 SCRIPT_PATHNAME="$(realpath $0)"
-UTILS=`dirname "$SCRIPT"`
-ROOT=`dirname "$UTILS"`
+UTILS=$(dirname "$SCRIPT_PATHNAME")
+ROOT=$(dirname "$UTILS")
+
+if [ ! -f "$ROOT/config/config.sh" ]; then
+    echo "Could not find configuration file" >&2
+    exit 1
+fi
 
 source $ROOT/config/config.sh
 
@@ -56,8 +64,5 @@ $PYTHON -m venv $ROOT/venv
 
 source $ROOT/venv/bin/activate
 
-pip install --upgrade pip
-pip install -r $ROOT/requirements.txt
-
-chown -R $HTTPD_USER:$HTTPD_USER $ROOT/venv
-
+pip install --no-cache-dir --upgrade pip
+pip install --no-cache-dir -r $ROOT/requirements.txt
