Added support for limiting auditing to files referenced in a specified audit error report
Updates to python imports

diff --git a/utils/appsupport/audit-project b/utils/appsupport/audit-project
--- a/utils/appsupport/audit-project
+++ b/utils/appsupport/audit-project
@@ -44,6 +44,7 @@ Usage: $SCRIPT PROJECT [OPTIONS]
        --timestamps 
        --checksums 
        (--report|--report-errors) [EMAIL] 
+       --error-file ERROR_FILE
 
        Where:
 
@@ -59,17 +60,18 @@ Usage: $SCRIPT PROJECT [OPTIONS]
        --report         auditing results will be emailed
        --report-errors  auditing results will be emailed, but only if errors are detected
        EMAIL            the email address where audit reports should be sent (defaults to configured recipient list)
+       ERROR_FILE       the pathname of the audit error file to be loaded
 
 If --changed-after and/or --changed-before are specified, files and folders which are outside the scope of files
 uploaded or frozen during the specified period, including changes only occurring in the filesystem and not known
 to Nextcloud, will not not be included in the audit; only changes which can be identified by timestamp updates in
 the Nextcloud or Metax databases which are within than the specified time period will be audited. To detect
 filesystem only changes you must perform an unrestricted audit without specifying any --changed-* parameters.
+
+If an audit error file is specified, then the new audit is limited only to files referenced in the audit error file.
 "
 
 # --------------------------------------------------------------------------------
-
-#START_ENV="$START" # allow start timestamp to be explicitly defined (used by tests)
 
 INIT_FILE=`dirname "$(realpath $0)"`/lib/init_audit_script.sh
 
@@ -84,20 +86,12 @@ fi
 
 SNAIL=`mail --version 2>/dev/null | grep -- 's-nail' 2>/dev/null`
 
-#if [ "$START_ENV" ]; then
-#    START="$START_ENV"
-#fi
+if [ ! -d "$PROJECT_STORAGE_OC_DATA_ROOT" ]; then
+    errorExit "The specified project ${PROJECT} does not exist"
+fi
 
 #--------------------------------------------------------------------------------
-
-REPORT_REQ=""
-RECIPIENTS=""
-FILE_AREA=""
-AFTER=""
-BEFORE=""
-FULL_AUDIT=""
-AUDIT_TIMESTAMPS=""
-AUDIT_CHECKSUMS=""
+# Process command line arguments...
 
 shift # got PROJECT from first argument via init_audit_script.sh
 
@@ -106,31 +100,38 @@ while [ "$1" ]; do
     case "$1" in
         "--full")
             if [ "$AFTER" ]; then
-                echo "Only one of --full or --changed-after is allowed"
+                echo "Only one of --full or --changed-after is allowed" >&2
                 exit 1
             fi
             if [ "$BEFORE" ]; then
-                echo "Only one of --full or --changed-before is allowed"
+                echo "Only one of --full or --changed-before is allowed" >&2
                 exit 1
             fi
-            if [ "$FILE_AREA" ]; then
-                echo "Only one of --full or $FILE_AREA is allowed"
+            if [ "$AUDIT_STAGING" ]; then
+                echo "Only one of --full or --staging is allowed" >&2
                 exit 1
             fi
-            FULL_AUDIT="$1"
-            AUDIT_TIMESTAMPS=""
-            AUDIT_CHECKSUMS=""
-            AFTER=""
-            BEFORE=""
-            FILE_AREA=""
+            if [ "$AUDIT_FROZEN" ]; then
+                echo "Only one of --full or --frozen is allowed" >&2
+                exit 1
+            fi
+            if [ "$ERROR_FILE" ]; then
+                echo "Only one of --full or --error-file is allowed" >&2
+                exit 1
+            fi
+            FULL_AUDIT="true"
             ;;
         "--changed-after")
-            if [ "$FULL_AUDIT" ]; then
-                echo "Only one of --full or --changed-after is allowed"
+            if [ "$FULL_AUDIT" = "true" ]; then
+                echo "Only one of --changed-after or --full is allowed" >&2
                 exit 1
             fi
-            if [ "$2" = "" ]; then
-                echo "Missing date[time] argument"
+            if [ "$ERROR_FILE" ]; then
+                echo "Only one of --changed-after or --error-file is allowed" >&2
+                exit 1
+            fi
+            if [ -z "$2" ]; then
+                echo "Missing date[time] argument" >&2
                 exit 1
             fi
             if [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}Z$ ]]; then
@@ -138,18 +139,22 @@ while [ "$1" ]; do
             elif [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}$ ]]; then
                 AFTER="$2""T00:00:00Z"
             else
-                echo "Invalid date[time]: $2"
+                echo "Invalid date[time]: $2" >&2
                 exit 1
             fi
             shift
             ;;
         "--changed-before")
-            if [ "$FULL_AUDIT" ]; then
-                echo "Only one of --full or --changed-before is allowed"
+            if [ "$FULL_AUDIT" = "true" ]; then
+                echo "Only one of --changed-before or --full is allowed" >&2
                 exit 1
             fi
-            if [ "$2" = "" ]; then
-                echo "Missing date[time] argument"
+            if [ "$ERROR_FILE" ]; then
+                echo "Only one of --changed-before or --error-file is allowed" >&2
+                exit 1
+            fi
+            if [ -z "$2" ]; then
+                echo "Missing date[time] argument" >&2
                 exit 1
             fi
             if [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}Z$ ]]; then
@@ -157,40 +162,103 @@ while [ "$1" ]; do
             elif [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}$ ]]; then
                 BEFORE="$2""T00:00:00Z"
             else
-                echo "Invalid date[time]: $2"
+                echo "Invalid date[time]: $2" >&2
                 exit 1
             fi
             shift
             ;;
-        "--staging" | "--frozen")
-            if [ "$FULL_AUDIT" ]; then
-                echo "Only one of --full or $1 is allowed"
+        "--staging")
+            if [ "$FULL_AUDIT" = "true" ]; then
+                echo "Only one of --full or --staging is allowed" >&2
                 exit 1
             fi
-            if [ "$FILE_AREA" ]; then
-                echo "Only one of --staging or --frozen is allowed"
+            if [ "$AUDIT_FROZEN" ]; then
+                echo "Only one of --staging or --frozen is allowed" >&2
                 exit 1
             fi
-            FILE_AREA="$1"
+            if [ "$ERROR_FILE" ]; then
+                echo "Only one of --error-file or --staging is allowed" >&2
+                exit 1
+            fi
+            AUDIT_STAGING="true"
+            ;;
+        "--frozen")
+            if [ "$FULL_AUDIT" = "true" ]; then
+                echo "Only one of --full or --frozen is allowed" >&2
+                exit 1
+            fi
+            if [ "$AUDIT_STAGING" ]; then
+                echo "Only one of --staging or --frozen is allowed" >&2
+                exit 1
+            fi
+            if [ "$ERROR_FILE" ]; then
+                echo "Only one of --error-file or --frozen is allowed" >&2
+                exit 1
+            fi
+            AUDIT_FROZEN="true"
             ;;
         "--timestamps")
-            AUDIT_TIMESTAMPS="$1"
+            if [ "$ERROR_FILE" ]; then
+                echo "Only one of --timestamps or --error-file is allowed" >&2
+                exit 1
+            fi
+            AUDIT_TIMESTAMPS="true"
             ;;
         "--checksums")
-            AUDIT_CHECKSUMS="$1"
+            if [ "$ERROR_FILE" ]; then
+                echo "Only one of --checksums or --error-file is allowed" >&2
+                exit 1
+            fi
+            AUDIT_CHECKSUMS="true"
+            ;;
+        "--error-file")
+            if [ "$FULL_AUDIT" = "true" ]; then
+                echo "Only one of --error-file or --full is allowed" >&2
+                exit 1
+            fi
+            if [ "$AFTER" ]; then
+                echo "Only one of --error-file or --changed-after is allowed" >&2
+                exit 1
+            fi
+            if [ "$BEFORE" ]; then
+                echo "Only one of --error-file or --changed-before is allowed" >&2
+                exit 1
+            fi
+            if [ "$AUDIT_STAGING" ]; then
+                echo "Only one of --error-file or --staging is allowed" >&2
+                exit 1
+            fi
+            if [ "$AUDIT_FROZEN" ]; then
+                echo "Only one of --error-file or --frozen is allowed" >&2
+                exit 1
+            fi
+            if [ "$AUDIT_TIMESTAMPS" ]; then
+                echo "Only one of --error-file or --timestamps is allowed" >&2
+                exit 1
+            fi
+            if [ "$AUDIT_CHECKSUMS" ]; then
+                echo "Only one of --error-file or --checksums is allowed" >&2
+                exit 1
+            fi
+            if [ ! -f "$2" ]; then
+                echo "Invalid audit error file pathname: $2" >&2
+                exit 1
+            fi
+            ERROR_FILE="$2"
+            shift
             ;;
         "--report" | "--report-errors")
             if [ "$REPORT_REQ" ]; then
-                echo "Only one of --report or --report-errors is allowed"
+                echo "Only one of --report or --report-errors is allowed" >&2
                 exit 1
             fi
-            REPORT_REQ="$1"
+            REPORT_REQ="${1:2}"
             ;;
         *)
-            if [ "$REPORT_REQ" != "" ] && [ "$RECIPIENTS" = "" ]; then
+            if [ "$REPORT_REQ" ] && [ -z "$RECIPIENTS" ]; then
                 RECIPIENTS="$1"
             else
-                echo "Invalid argument: $1"
+                echo "Invalid argument: $1" >&2
                 exit 1
             fi
             ;;
@@ -200,35 +268,20 @@ while [ "$1" ]; do
 
 done
 
-if [ "$REPORT_REQ" != "" ]; then
-    if [ "$RECIPIENTS" = "" ]; then
+if [ "$REPORT_REQ" ]; then
+    if [ -z "$RECIPIENTS" ]; then
         RECIPIENTS="$EMAIL_RECIPIENTS"
     fi
 fi
 
 # If after timestamp not specified, use the unix epoch
-if [ "$AFTER" = "" ]; then
+if [ -z "$AFTER" ]; then
     AFTER="1970-01-01T00:00:00Z"
 fi
 
 # If before timestamp not specified, use the start time
-if [ "$BEFORE" = "" ]; then
+if [ -z "$BEFORE" ]; then
     BEFORE="$START"
-fi
-
-AUDIT_ARGS="${FULL_AUDIT} ${FILE_AREA} ${AUDIT_TIMESTAMPS} ${AUDIT_CHECKSUMS}"
-
-#--------------------------------------------------------------------------------
-
-if [ "$DEBUG" = "true" ]; then
-    echo "ROOT:       $ROOT"
-    echo "PROJECT:    $PROJECT"
-    echo "AFTER:      $AFTER"
-    echo "BEFORE:     $BEFORE"
-    echo "START:      $START"
-    echo "AUDIT_ARGS: $AUDIT_ARGS"
-    echo "REPORT_REQ: $REPORT_REQ"
-    echo "RECIPIENTS: $RECIPIENTS"
 fi
 
 if [[ "$AFTER" == "$START" || "$AFTER" > "$START" ]]; then
@@ -243,10 +296,6 @@ fi
 
 #--------------------------------------------------------------------------------
 
-if [ ! -d "$PROJECT_STORAGE_OC_DATA_ROOT" ]; then
-    errorExit "The specified project ${PROJECT} does not exist"
-fi
-
 LOG_ROOT=`dirname "$(realpath $LOG)"`
 YEAR=`date -u +"%Y"`
 MONTH=`date -u +"%m"`
@@ -257,12 +306,42 @@ mkdir -p $REPORT_ROOT/$YEAR/$MONTH 2>/dev/null
 
 #--------------------------------------------------------------------------------
 
+if [ "$DEBUG" = "true" ]; then
+    echo "ROOT:             $ROOT"
+    echo "PROJECT:          $PROJECT"
+    echo "START:            $START"
+    echo "AFTER:            $AFTER"
+    echo "BEFORE:           $BEFORE"
+    echo "FULL_AUDIT:       $FULL_AUDIT"
+    echo "AUDIT_STAGING:    $AUDIT_STAGING"
+    echo "AUDIT_FROZEN:     $AUDIT_FROZEN"
+    echo "AUDIT_TIMESTAMPS: $AUDIT_TIMESTAMPS"
+    echo "AUDIT_CHECKSUMS:  $AUDIT_CHECKSUMS"
+    echo "ERROR_FILE:       $ERROR_FILE"
+    echo "REPORT_REQ:       $REPORT_REQ"
+    echo "RECIPIENTS:       $RECIPIENTS"
+fi
+
+#--------------------------------------------------------------------------------
+
 OUTPUT="/var/tmp/$$.out"
 SUMMARY="$OUTPUT.summary"
 
 source $ROOT/venv/bin/activate
 
-python -u $ROOT/utils/appsupport/lib/audit_project.py $ROOT $PROJECT $START $AFTER $BEFORE $AUDIT_ARGS > $OUTPUT
+export ROOT
+export PROJECT
+export START
+export AFTER
+export BEFORE
+export FULL_AUDIT
+export AUDIT_STAGING
+export AUDIT_FROZEN
+export AUDIT_TIMESTAMPS
+export AUDIT_CHECKSUMS
+export ERROR_FILE
+
+python -u $ROOT/utils/appsupport/lib/audit_project.py > $OUTPUT
 
 if [ "$?" -ne 0 ]; then
     rm $OUTPUT 2>/dev/null
@@ -289,13 +368,13 @@ fi
 
 SEND_REPORT="false"
 
-if [ "$REPORT_REQ" = "--report" ]; then
+if [ "$REPORT_REQ" = "report" ]; then
     SEND_REPORT="true"
 fi
 
-OK=`head -15 $REPORT_BASE | grep "\"invalidNodeCount\" *: *0\b"`
+OK=`head -20 $REPORT_BASE | grep "\"invalidNodeCount\" *: *0\b"`
 
-if [ "$OK" != "" ]; then
+if [ "$OK" ]; then
    OK="true"
 else
    OK="false"
@@ -305,7 +384,7 @@ if [ "$OK" = "true" ]; then
     REPORT="$REPORT_BASE.OK.json"
 else
     REPORT="$REPORT_BASE.ERR.json"
-    if [ "$REPORT_REQ" = "--report-errors" ]; then
+    if [ "$REPORT_REQ" = "report-errors" ]; then
         SEND_REPORT="true"
     fi
 fi
@@ -334,7 +413,7 @@ if [ "$DEBUG" = "true" ]; then
     echo "RECIPIENTS:    $RECIPIENTS"
 fi
 
-if [ "$SEND_REPORT" = "true" ] && [ "$RECIPIENTS" != "" ]; then
+if [ "$SEND_REPORT" = "true" ] && [ "$RECIPIENTS" ]; then
 
     HOSTNAME=`hostname`
 
